"""make readers

Revision ID: 13846616608b
Revises: a5cb799c1df8
Create Date: 2023-06-09 11:33:14.014019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13846616608b'
down_revision = 'a5cb799c1df8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('readers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('readers')
    # ### end Alembic commands ###
